[package]
name = "rill-telegram-bot"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
teloxide.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true
