[package]
name = "rill-source-rss"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
feed-rs.workspace = true
quick-xml.workspace = true
rill-domain = { path = "../domain" }
rill-source-api = { path = "../source-api" }
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
url.workspace = true
uuid.workspace = true

